# Define Organization Entities
Organizations:
  - &QQ
    Name: QQ # Name of the organization
    ID: QQMSP # MSPID of the organization
    MSPDir: crypto-config/ordererOrganizations/qq.com/msp # Relative path to the organization's certificates (generated in the crypto-config directory)

  - &Taobao
    Name: Taobao
    ID: TaobaoMSP
    MSPDir: crypto-config/peerOrganizations/taobao.com/msp
    AnchorPeers: # Configuration for organization's anchor peers
      - Host: peer0.taobao.com
        Port: 7051

  - &JD
    Name: JD
    ID: JDMSP
    MSPDir: crypto-config/peerOrganizations/jd.com/msp
    AnchorPeers: # Configuration for organization's anchor peers
      - Host: peer0.jd.com
        Port: 7051

# Define parameters related to the orderer service, which will be used to create the genesis block
Orderer: &OrdererDefaults
  # OrdererType specifies the type of orderer node to enable, different implementations correspond to different consensus algorithms
  OrdererType: solo # Consensus mechanism
  Addresses: # Orderer's domain names (used for connection)
    - orderer.qq.com:7050
  BatchTimeout: 2s # Time interval for creating blocks
  BatchSize: # Used to control the amount of information in each block
    MaxMessageCount: 10 # Number of messages per block
    AbsoluteMaxBytes: 99 MB # Maximum size of each block's information
    PreferredMaxBytes: 512 KB # Maximum length of a single message included in each block
  Organizations:

# Define how Peer organizations interact with the application channel
# Default policy: All Peer organizations can read and write data to the ledger
Application: &ApplicationDefaults
  Organizations:

# Define the configuration entry for the configtxgen tool
# Specify the Profile parameter (TwoOrgsOrdererGenesis or TwoOrgsChannel) as a parameter for the configtxgen tool
Profiles:
  # TwoOrgsOrdererGenesis configuration file is used to create the system channel's genesis block
  # This configuration file creates a consortium named SampleConsortium
  # The consortium in this configtx.yaml file consists of two Peer organizations: Taobao and JD
  TwoOrgsOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *QQ
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Taobao
          - *JD
  # Use the TwoOrgsChannel configuration file to create the application channel
  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Taobao
        - *JD
