# Definition of Orderer Organizations
OrdererOrgs:
  - Name: QQ # Name
    Domain: qq.com # Domain
    Specs: # Node domain: orderer.qq.com
      - Hostname: orderer # Hostname

# Definition of Peer Organizations
PeerOrgs:
  # Taobao Organization
  - Name: Taobao # Name
    Domain: taobao.com # Domain
    Template: # Definition using a template. Count refers to the number of organization nodes in this organization
      Count: 2 # Node domains: peer0.taobao.com and peer1.taobao.com
    Users: # Organization user information. Count specifies the number of users in this organization other than Admin
      Count: 1 # Users: Admin and User1

  # JD Organization
  - Name: JD
    Domain: jd.com
    Template:
      Count: 2 # Node domains: peer0.jd.com and peer1.jd.com
    Users:
      Count: 1 # Users: Admin and User1